import * as i0 from "@angular/core";
import * as i1 from "./hello-world";

// BEGIN class generated by kotlin compiler 
export const HelloWorldModule = /* @constructor */ function() {};
// END class generated by kotlin compiler 

HelloWorldModule.ngModuleDef = i0.ɵdefineNgModule({ type: HelloWorldModule, bootstrap: [], declarations: [i1.HelloWorld], imports: [], exports: [] });
